/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: '#C45B28',
        secondary: '#4A8C5C',
        'accent-gold': '#C49B28',
        'accent-olive': '#6B8C3A',
        bg: '#FAF6F0',
        surface: '#FFFFFF',
        'surface-warm': '#FFF8ED',
        border: '#E8DDD0',
        'border-light': '#F0E6D8',
        'text-primary': '#3D2E1F',
        'text-secondary': '#6B5A48',
        'text-tertiary': '#8C7B6B',
        'text-placeholder': '#B8ADA0',
        protein: '#C45B28',
        carbs: '#C49B28',
        fat: '#4A8C5C',
        veggies: '#6B8C3A',
        success: '#4A8C5C',
        'prep-day': '#4A8C5C',
        'dine-out': '#C49B28',
        'ai-surface': '#FFF8ED',
        'ai-accent': '#C49B28',
        'dark-bg': '#3D2E1F',
        'dark-text': '#FFFFFF',
        'dark-text-muted': 'rgba(255, 255, 255, 0.5)',
        'protein-bg': '#FDF5EE',
        'carbs-bg': '#FBF6E8',
        'fat-bg': '#EDF5F0',
        'veggies-bg': '#F2F5EC',
      },
      fontSize: {
        xs: '10px',
        sm: '11px',
        'body-sm': '12px',
        body: '13px',
        'body-lg': '14px',
        input: '14px',
        'card-title': '15px',
        section: '16px',
        'screen-title': '18px',
        heading: '20px',
        'page-title': '22px',
        timer: '42px',
      },
      spacing: {
        xs: '4px',
        sm: '6px',
        md: '8px',
        lg: '10px',
        xl: '12px',
        '2xl': '14px',
        '3xl': '16px',
        '4xl': '18px',
        '5xl': '20px',
        'page-padding': '20px',
      },
      borderRadius: {
        sm: '6px',
        md: '8px',
        lg: '10px',
        card: '12px',
        'card-lg': '14px',
        'active-step': '16px',
        page: '24px',
      },
    },
  },
  plugins: [],
}
