import json
import logging
from fastapi import APIRouter, Depends, HTTPException, Query
from sqlalchemy.orm import Session
from typing import List, Optional

from app.db.models import Recipe
from app.db.session import get_db
from app.schemas.recipe import RecipeIn, RecipeOut, RecipeUpdate
from app.services import nutrition

logger = logging.getLogger(__name__)

router = APIRouter()


def _parse_recipe_to_out(recipe: Recipe) -> RecipeOut:
    """Helper to convert DB Recipe model to RecipeOut schema, parsing JSON fields."""
    ingredients = json.loads(recipe.ingredients) if recipe.ingredients else []
    prep_steps = json.loads(recipe.prep_steps) if recipe.prep_steps else []
    serving_instructions = json.loads(recipe.serving_instructions) if recipe.serving_instructions else None
    tags = json.loads(recipe.tags) if recipe.tags else None

    return RecipeOut(
        id=recipe.id,
        display_name=recipe.display_name,
        authentic_name=recipe.authentic_name,
        description=recipe.description,
        cuisine=recipe.cuisine,
        ingredients=ingredients,
        prep_steps=prep_steps,
        serving_instructions=serving_instructions,
        prep_time_min=recipe.prep_time_min,
        cook_time_min=recipe.cook_time_min,
        reheat_time_min=recipe.reheat_time_min,
        shelf_life_days=recipe.shelf_life_days,
        storage_notes=recipe.storage_notes,
        tags=tags,
        is_batch_prep=recipe.is_batch_prep,
        is_favorite=recipe.is_favorite,
        is_disliked=recipe.is_disliked,
        calories_per_serving=recipe.calories_per_serving,
        protein_g=recipe.protein_g,
        carbs_g=recipe.carbs_g,
        fat_g=recipe.fat_g,
        veggie_servings=recipe.veggie_servings
    )


@router.get("", response_model=List[RecipeOut])
def get_recipes(
    cuisine: Optional[str] = None,
    tags: Optional[str] = Query(None, description="Comma-separated list of tags, match any"),
    favorites: Optional[bool] = None,
    limit: int = 50,
    db: Session = Depends(get_db)
):
    """List saved recipes with optional filters."""
    query = db.query(Recipe)

    # Apply cuisine filter
    if cuisine is not None:
        query = query.filter(Recipe.cuisine == cuisine)

    # Apply favorites filter
    if favorites is not None:
        query = query.filter(Recipe.is_favorite == favorites)

    # Fetch matching recipes up to limit
    recipes = query.limit(limit).all()

    # Apply tags filter (match any tag in comma-separated list)
    if tags is not None:
        tag_list = [t.strip() for t in tags.split(",") if t.strip()]
        filtered_recipes = []
        for recipe in recipes:
            recipe_tags = json.loads(recipe.tags) if recipe.tags else []
            if any(tag in recipe_tags for tag in tag_list):
                filtered_recipes.append(recipe)
        recipes = filtered_recipes

    # Convert to response schema
    return [_parse_recipe_to_out(r) for r in recipes]


@router.get("/{recipe_id}", response_model=RecipeOut)
def get_recipe(recipe_id: str, db: Session = Depends(get_db)):
    """Get recipe by ID, 404 if not found."""
    recipe = db.query(Recipe).filter(Recipe.id == recipe_id).first()
    if not recipe:
        raise HTTPException(status_code=404, detail="Recipe not found")
    return _parse_recipe_to_out(recipe)


@router.post("", response_model=RecipeOut, status_code=201)
async def create_recipe(recipe_in: RecipeIn, db: Session = Depends(get_db)):
    """Create a new recipe and auto-resolve nutrition."""
    # Convert list fields to JSON strings for storage
    ingredients_json = json.dumps([ing.model_dump() for ing in recipe_in.ingredients])
    prep_steps_json = json.dumps(recipe_in.prep_steps)
    serving_instructions_json = json.dumps(recipe_in.serving_instructions) if recipe_in.serving_instructions else None
    tags_json = json.dumps(recipe_in.tags) if recipe_in.tags else None

    # Create DB record (ID auto-generated by model default)
    db_recipe = Recipe(
        display_name=recipe_in.display_name,
        authentic_name=recipe_in.authentic_name,
        description=recipe_in.description,
        cuisine=recipe_in.cuisine,
        ingredients=ingredients_json,
        prep_steps=prep_steps_json,
        serving_instructions=serving_instructions_json,
        prep_time_min=recipe_in.prep_time_min,
        cook_time_min=recipe_in.cook_time_min,
        reheat_time_min=recipe_in.reheat_time_min,
        shelf_life_days=recipe_in.shelf_life_days,
        storage_notes=recipe_in.storage_notes,
        tags=tags_json,
        is_batch_prep=recipe_in.is_batch_prep,
        is_favorite=recipe_in.is_favorite,
        is_disliked=recipe_in.is_disliked,
        # Macros intentionally left null, will be filled by nutrition resolution
        calories_per_serving=None,
        protein_g=None,
        carbs_g=None,
        fat_g=None
    )

    db.add(db_recipe)
    db.commit()
    db.refresh(db_recipe)
    
    # Auto-resolve nutrition after initial write
    try:
        await nutrition.resolve_recipe_nutrition(db_recipe, db)
        db.refresh(db_recipe)
        logger.info(f"Resolved nutrition for new recipe {db_recipe.id}")
    except Exception as e:
        logger.error(f"Failed to resolve nutrition for recipe {db_recipe.id}: {e}")

    return _parse_recipe_to_out(db_recipe)


@router.patch("/{recipe_id}", response_model=RecipeOut)
async def update_recipe(
    recipe_id: str,
    recipe_update: RecipeUpdate,
    db: Session = Depends(get_db)
):
    """Partial update of a recipe by ID, 404 if not found. Auto-resolves nutrition if ingredients changed."""
    db_recipe = db.query(Recipe).filter(Recipe.id == recipe_id).first()
    if not db_recipe:
        raise HTTPException(status_code=404, detail="Recipe not found")

    # Track if ingredients were updated
    ingredients_updated = False

    # Update only provided fields
    if recipe_update.display_name is not None:
        db_recipe.display_name = recipe_update.display_name
    if recipe_update.authentic_name is not None:
        db_recipe.authentic_name = recipe_update.authentic_name
    if recipe_update.description is not None:
        db_recipe.description = recipe_update.description
    if recipe_update.cuisine is not None:
        db_recipe.cuisine = recipe_update.cuisine
    if recipe_update.ingredients is not None:
        db_recipe.ingredients = json.dumps([ing.model_dump() for ing in recipe_update.ingredients])
        ingredients_updated = True
    if recipe_update.prep_steps is not None:
        db_recipe.prep_steps = json.dumps(recipe_update.prep_steps)
    if recipe_update.serving_instructions is not None:
        db_recipe.serving_instructions = json.dumps(recipe_update.serving_instructions)
    if recipe_update.prep_time_min is not None:
        db_recipe.prep_time_min = recipe_update.prep_time_min
    if recipe_update.cook_time_min is not None:
        db_recipe.cook_time_min = recipe_update.cook_time_min
    if recipe_update.reheat_time_min is not None:
        db_recipe.reheat_time_min = recipe_update.reheat_time_min
    if recipe_update.shelf_life_days is not None:
        db_recipe.shelf_life_days = recipe_update.shelf_life_days
    if recipe_update.storage_notes is not None:
        db_recipe.storage_notes = recipe_update.storage_notes
    if recipe_update.tags is not None:
        db_recipe.tags = json.dumps(recipe_update.tags)
    if recipe_update.is_batch_prep is not None:
        db_recipe.is_batch_prep = recipe_update.is_batch_prep
    if recipe_update.is_favorite is not None:
        db_recipe.is_favorite = recipe_update.is_favorite
    if recipe_update.is_disliked is not None:
        db_recipe.is_disliked = recipe_update.is_disliked

    db.commit()
    db.refresh(db_recipe)
    
    # Only resolve nutrition if ingredients were changed
    if ingredients_updated:
        try:
            await nutrition.resolve_recipe_nutrition(db_recipe, db)
            db.refresh(db_recipe)
            logger.info(f"Resolved nutrition for updated recipe {recipe_id} (ingredients changed)")
        except Exception as e:
            logger.error(f"Failed to resolve nutrition for recipe {recipe_id}: {e}")

    return _parse_recipe_to_out(db_recipe)
